class PlayingCard {
  late String? name;
  late List<String>? names;
  late String? manaCost;
  late int? cmc;
  var variations;
  var watermark;
  var border;
  var timeShifted;
  var hand;
  var reserved;
  var releaseDate;
  var starter;
  var rulings;
  late List<String>? colors;
  late List<String>? colorIdentity;
  late String? type;
  late List<String>? supertypes;
  late List<String>? types;
  late List<String>? subtypes;
  late String? rarity;
  late String? set;
  late String? setName;
  late String? text;
  late String? flavor;
  late String? artist;
  late String? number;
  late String? power;
  late String? toughness;
  late int? loyality;
  late List<String> gameFormats;
  var legality;
  var legalities;
  // var page;
  // var pageSize;
  // var orderBy;
  late String? layout;
  late String? multiverseId;
  var imageUrl;
  var printings;
  var originalType;
  var originalText;
  var source;
  var Id;

  PlayingCard(var json) {
    this.name = json["name"];
    this.names = json["names"]?.cast<String>();
    this.cmc = json["cmc"]?.toInt();
    this.type = json["type"];
    this.types = json["types"]?.cast<String>();
    this.rarity = json["rarity"];
    this.set = json["set"];
    this.setName = json["setName"];
    this.text = json["text"];
    this.flavor = json["flavor"];
    this.artist = json["artist"];
    this.number = json["number"];
    this.layout = json["layout"];
    this.multiverseId = json["multiverseid"];
    this.imageUrl = json["imageUrl"];
    this.printings = json["printings"];
    this.originalType = json["originalType"];
    this.Id = json["id"];
    this.legalities = json["legalities"];
    printCard();
  }
  printCard() {
    print(name);
    print(cmc);
    print(type);
    print(types);
    print(rarity);
    print(text);
    print(set);
    print(setName);
    print(flavor);
    print(artist);
    print(number);
    print(layout);
    print(multiverseId);
    print(imageUrl);
    print(printings);
    print(originalType);
    print(Id);
    print(legalities);
  }
}
